### PR TITLE
Fix date format constant for version check.

### PR DESCRIPTION
**Pull request by minnoroth**
Change `VERSION_DATE_FORMAT` constant in order to prevent version check raising an exception: `java.text.ParseException: Unparseable date: "2023-02-22T13:35:15Z"`

### CODE REVIEW

**Comment by pavelhoral** [comment]
Were you able to find where (by which commit) this inconsistency was introduced?

**Comment by minnoroth** [comment]
Updated the commit message with the number of the issue.

The inconsistency was first introduced by this commit:
https://github.com/wrensecurity/wrenam/commit/cf19dc3c0aa1c4e56e355d20ce5d25546accc46b

**Comment by pavelhoral** [comment]
Implemented changes does not feel complete - i.e. changing unit tests without checking what those tests are checking is suspicious.

By a quick search you can find that the DATE_FORMAT constant is used in [`VersionUtils`](https://github.com/WrenSecurity/wrenam/blob/a5a22f8023b0bdf191c5f5caa662257396f24b49/openam-core/src/main/java/org/forgerock/openam/upgrade/VersionUtils.java) where there are multiple patterns and logic that uses UK based date format / locale. Also please be aware that by switching to ISO date format does not mean that we can expect that that is the format used in an installation that is being upgraded.

**Review by pavelhoral — APPROVED** [review]
LGTM after refactoring

**Review by karelmaxa — APPROVED** [review]
LGTM.

**Pull request merged**
